### ISSUE TITLE
Determine naming patterns for remaining AM4 board types

### ISSUE THREAD

**Issue by iAmSomeone2** [iAmSomeone2/asus_bios_renamer#3]
Currently, TUF AM4 boards are the only models that this program can handle. Boards in the Strix, Crosshair, etc. lineups use different name transformations for their BIOS files. Additionally, Intel boards in the same product families appear to use different patterns to their AMD counterparts. For this program to be truly useful, as many boards as possible must be supported.

This research task will focus on understanding the transformation patterns for the remaining AM4 boards.

**Comment by h454n5** [comment]
So there's only a handful of Asus boards that support **USB BIOS flashback**.

> 
> #Asus X570
> Asus ROG Crosshair VIII Formula (ATX)
> Asus ROG Crosshair VIII Hero (ATX)
> Asus ROG Crosshair VIII Hero WiFi (ATX)
> Asus ROG Crosshair VIII Hero Dark (ATX)
> Asus TUF Gaming X570-PRO WiFi (ATX)
> Asus ROG Strix X570-E (ATX)
> Asus ROG X570-F (ATX)
> Asus ROG Crosshair VIII Impact (mDTX)
> 
> #Asus B550
> Asus TUF B550M-Plus WiFi (mATX)
> Asus ROG Strix B550-I (mITX)
> Asus ROG Strix B550-A (ATX)
> Asus ROG Strix B550-E (ATX)
> Asus ROG Strix B550-F (ATX)
> Asus ROG Strix B550-F WiFi (ATX)
> Asus ROG Strix B550-XE WiFi (ATX)
> Asus TUF Gaming B550-Plus (ATX)
> Asus TUF Gaming B550-Plus WiFi (ATX)
> 
> #Asus B450
> Asus TUF Gaming B450M-Plus II (mATX)
> Asus TUF Gaming B450M-Pro S (mATX)
> Asus Prime B450M-A II (mATX)
> Asus ROG Strix B450-F Gaming II (ATX)
> 
> #Asus x470
> ASUS Crosshair VII Hero (ATX)
> ASUS Crosshair VII Hero Wi-Fi (ATX)
> 
> #Asus z490
> Asus ROG Maximus XII Extreme (EATX)
> Asus ROG Maximus XII Hero Wi-Fi (ATX)
> Asus ROG Strix Z490-E Gaming (ATX)

Maybe an easy method to get this working reliably would be to just go out and find the filename ASUS uses for each one on the support site, then creating a simple rust function to return the right filename.

```rust 
fn test(value: &str) -> usize {
    // Match on string that contains the filename, with the end stripped out
    match value {
        "ROG-CROSSHAIR-VIII-DARK-HERO-ASUS" => println!("C8DH.CAP"),
        "ROG-CROSSHAIR-VIII-FORMULA-ASUS" => println!("C8F.CAP"),
        "ROG-CROSSHAIR-VIII-HERO-ASUS" => println!("C8H.CAP"),
        "ROG-CROSSHAIR-VIII-HERO-WIFI-ASUS" => println!("C8HW.CAP"),
        _ => 0
    }
}
```

**Comment by iAmSomeone2** [comment]
I considered that, but didn't know how many boards used USB BIOS Flashback. I ended up digging into the BIOS files themselves and found a data structure that contains a bunch of useful info; including the expected name of the .CAP file!

I made a new `dev` branch that's essentially a complete rewrite of the app. I tested it on a couple files, and it worked well. I definitely haven't tried with the entire list that you found, but I could download some of those to make sure they work.

**Comment by iAmSomeone2** [comment]
The new method also has the advantage of working regardless of what the file is named. It could be `foo.bar` and as long as the file isn't corrupted, the app will successfully rename it.

I'm currently determining some methods to detect if the BIOS files are corrupted. So far, it looks like they're all the same size, so that could maybe be one check.
