### ISSUE TITLE
does not work with bios for proart-x670e-creator-wifi

### ISSUE THREAD

**Issue by darix** [iAmSomeone2/asus_bios_renamer#5]
https://www.asus.com/motherboards-components/motherboards/proart/proart-x670e-creator-wifi/helpdesk_bios/?model2Name=ProArt-X670E-CREATOR-WIFI

it gets a very weird binary filename

**Comment by iAmSomeone2** [comment]
Thanks for the heads up! There's a good chance that this board stores the expected name in a different place than the generation of boards that I built this tool to target. The program is just grabbing whatever bytes are at the expected location and making a string out of them.

I have an idea on how I might fix this. I'll keep this issue updated as work progresses.
